#!/bin/sh

# On my development machine, this easily between the local FSTs that I know
# work, and the development/experimental FSTs.
#
# itwêwina searches for FSTs in /opt/smi/crk/bin, so create the appropriate
# symlinks.

case "$1" in
    local)
        TARGET="$(dirname "$(realpath "$0")")/custom-fsts"
        ;;
    devel)
        TARGET="${GTLANG_crk:?}/src"
        ;;
    *)
        echo "$(basename "$0"): argument must be 'local' or 'devel'" 1>&2
        exit 2
        ;;
esac

ensure_exists() {
    fst="$TARGET/$1" 
    test -r "$fst" && return
    echo "Could not find $1 in $TARGET" 1>&2
    exit 1
}

ensure_exists analyser-gt-desc.hfstol
ensure_exists generator-gt-dict-norm.hfstol
ensure_exists generator-gt-norm.Cans-to-Cans.hfstol
ensure_exists analyser-gt-desc.Cans-to-Cans.hfstol

# Make the symlink!
ln -shf "$TARGET" /opt/smi/crk/bin
